### PR TITLE
Update org.openchemistry.Avogadro2.Molequeue.desktop

### PR DESCRIPTION
**Pull request by ovari**
https://github.com/OpenChemistry/avogadroapp/issues/217

### CODE REVIEW

**Comment by ovari** [comment]
@ghutchis can you please accept this merge request? Thank you

**Comment by ovari** [comment]
Seems that we did something wrong as the checks failed. Please advise what we need to do. Thank you

**Comment by kevinsmia1939** [comment]
@ovari 
Hi,

Change the checksum under
```
      - type: archive
        url: https://github.com/OpenChemistry/avogadro-i18n/archive/refs/heads/master.zip
        dest: avogadro-i18n
```
b2bc8b505a5e01bc3b29e71852ffd8a8a319cc9bb360372f4a91217b73e1f5e5
to 
afed4f3b8d09f977b023e68596edcf8958fc6dae32bc661cee72380a31a61d6a

There is an update in avogadro-i18n, so sha256 will need to be change.

**Comment by ovari** [comment]
@kevinsmia1939 thank you for your comment.

Hopefully we have done what you asked correctly.

If not, you are welcome to update.

Thank you

**Pull request merged**
