### PR TITLE
Massively simplify build process by using the normal upstream build, add beta

### PR DESCRIPTION
**Pull request by matterhorn103**
The Avogadro project provides nightly builds for other platforms. Though this is nightly, it is pretty stable, and is generally the recommended version of the program to use. However, as flathub (completely reasonably) discourages overloading their CI with nightly build pushes, the intention instead is to provide a beta flatpak branch that updates perhaps once a week rather than once a day, as a sort of equivalent to the nightly AppImage.

This PR sets this up. Initially the commit hashes will be updated manually at regular intervals.

At the same time, we want to align the build process of the flatpak as closely as possible with that used for the normal releases and GitHub Actions builds. Consistent environments and build strategies across platforms will make support much easier and will also allow us to integrate the build of a flatpak bundle into our CI workflow.

This harmonization has been worked at at both ends:

- the new manifest is massively simplified and, instead of building the dependencies itself, now reuses the build process from the upstream project repo
- the same build options are being used as upstream
- components that are not currently being bundled upstream are no longer bundled in the flatpak either
- metadata/desktop files are instead hosted and used from upstream
- further changes to the upstream repos to bring everything in line with XDG standards and guidelines have been made or are in progress

We are also actively striving to fulfil the quality guidelines and make the flatpak more idiomatic, and a few first steps towards that are taken already within this. This includes for example significantly reducing the permissions required.

Once the build and upload to flathub is verified to work correctly and all pieces are in place upstream the intention is to change the master/stable manifest to match, but to point at the latest stable release rather than recent commits.

### CODE REVIEW

**Comment by matterhorn103** [comment]
bot, build

**Comment by kevinsmia1939** [comment]
Thank so much for your help.

**Comment by matterhorn103** [comment]
bot, build

**Comment by matterhorn103** [comment]
> Thank so much for your help.

Very happy to! You don't visit the Avogadro forums all that often right? So where is the easiest place to discuss the flatpak maintenance and strategy and so on - here on GitHub or on the forum or via email or on Discord or what?

**Comment by matterhorn103** [comment]
bot, build

**Comment by matterhorn103** [comment]
bot, build

**Comment by kevinsmia1939** [comment]
I mostly visit github and look thought my notification sometimes.

**Pull request merged**
